apply plugin: 'com.android.library'



android {
  compileSdk = COMPILE_SDK_VERSION.toInteger()

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
      minSdkVersion = TRITONSDK_MIN_SDK_VERSION.toInteger()
      targetSdkVersion = TARGET_SDK_VERSION.toInteger()
    }

  libraryVariants.all { variant ->
    variant.outputs.all { output ->
      outputFileName = "triton-android-sdk-${tritonSDKVersion}.aar"
    }
  }
  namespace = 'com.tritondigital.tdsdk'
}

dependencies {
  implementation fileTree(include: ['*.jar'], dir: 'libs')
}

clean {
  delete fileTree('libs') {
    include '*.aar', '*.jar'
  }
}
